/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageSevenTwo.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageSevenTwo: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageSevenTwo()
	{
		this.StartPassage = "Diner with Orphan";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Diner with Orphan

	void passage1_Init()
	{
		this.Passages[@"Diner with Orphan"] = new StoryPassage(@"Diner with Orphan", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros3.SetSpeaker("George");
		yield return lineBreak();
		yield return text("\"...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Hey, remember me?\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Of course I remember,\" George says. \"I'm an orphan, not a dumbass. You don't have to talk to me like I'm a little kid.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Fine then. How are you doing today, George?\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"I'm doing alright. Why do you ask?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Just wondering.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"You ask too many questions,\" George sighs. \"Keep poking your nose around like that and eventually it'll get chopped off.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That's a...colorful...expression. ", " 5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"It's what they taught us at the orphanage. Hands, ears, and eyes to ourselves. Don't peek, and you won't get beat.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"So they really beat you at the orphanage?\" ", " 6", null);
		yield break;
	}


	// .............
	// #6:  6

	void passage6_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"That's just the tip of the iceberg. Sometimes, they'd have the other kids rough you up, and they'd just sit and watch...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"This sounds pretty awful. ", " 7", null);
		yield break;
	}


	// .............
	// #7:  7

	void passage7_Init()
	{
		this.Passages[@" 7"] = new StoryPassage(@" 7", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"It was. I'm glad it's gone, to be honest.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Just how did you get out, by the way? The fire started at the orphanage, right? So how were you the only survivor?\" ", " 8", null);
		yield break;
	}


	// .............
	// #8:  8

	void passage8_Init()
	{
		this.Passages[@" 8"] = new StoryPassage(@" 8", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"There you go with the questions again. So irritating.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You didn't answer the question.\" ", " 9", null);
		yield break;
	}


	// .............
	// #9:  9

	void passage9_Init()
	{
		this.Passages[@" 9"] = new StoryPassage(@" 9", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"Fine,\" he grumbles. \"I was in bed when I thought I smelled smoke, so I hopped out of bed and ran out the front door. Guess I must have been faster than the rest, because no one else got out before the place burst into flames.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That sounds reasonable. Lucky you.\" ", " 10", null);
		yield return lineBreak();
		yield return link("\"Sounds a little fishy to me.\" ", " 10", null);
		yield break;
	}


	// .............
	// #10:  10

	void passage10_Init()
	{
		this.Passages[@" 10"] = new StoryPassage(@" 10", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"I don't need your approval. I was there. I know what happened.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Right...\" ", " 11", null);
		yield break;
	}


	// .............
	// #11:  11

	void passage11_Init()
	{
		this.Passages[@" 11"] = new StoryPassage(@" 11", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("George scoffs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"You don't believe me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"So where do you think the fire started? The basement?\" ", " 12", null);
		yield break;
	}


	// .............
	// #12:  12

	void passage12_Init()
	{
		this.Passages[@" 12"] = new StoryPassage(@" 12", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"Err, the orphanage doesn't have a basement...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You don't need to lie, I've seen it for myself. ", "13", null);
		yield return lineBreak();
		yield return link("\"Oh, my mistake.\" ", " 13", null);
		yield break;
	}


	// .............
	// #13: 13

	void passage13_Init()
	{
		this.Passages[@"13"] = new StoryPassage(@"13", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"...I really have no idea what you're talking about. A-and I'm starting to get a little tired. Can we continue this some other time?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Alright, George. Talk to you later. ", " 14", null);
		yield break;
	}


	// .............
	// #14:  13

	void passage14_Init()
	{
		this.Passages[@" 13"] = new StoryPassage(@" 13", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("\"Yeah...a-anyways, why don't we call it a day? I'm feeling pretty tired...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Sounds good to me. See you later, George.\" ", " 14", null);
		yield break;
	}


	// .............
	// #15:  14

	void passage15_Init()
	{
		this.Passages[@" 14"] = new StoryPassage(@" 14", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\"See you...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield break;
	}


	// .............
	// #16:  EndDia

	void passage16_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		macros3.EndDialogue(" ");
		yield break;
	}


}