/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageEight.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageEight: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageEight()
	{
		this.StartPassage = "Orphanage with Sheriff";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Orphanage with Sheriff

	void passage1_Init()
	{
		this.Passages[@"Orphanage with Sheriff"] = new StoryPassage(@"Orphanage with Sheriff", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros3.SetSpeaker("Sheriff");
		yield return lineBreak();
		yield return text("\"Hey, you.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Good to see you too, sheriff.\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"I see you're still in one piece,\" he says with a crooked smile. \"Couldn't be sure, after the men in black came by to scare you.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I wasn't scared.\" ", " 3", null);
		yield return lineBreak();
		yield return link("\"I'll be honest, they got me a little nervous.\" ", " 3.5", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Well, aren't you brave? Why don't you lead the way? And give me the rundown while we're at it.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"There's something below the orphanage that you need to see.\" ", "4", null);
		yield break;
	}


	// .............
	// #4:  3.5

	void passage4_Init()
	{
		this.Passages[@" 3.5"] = new StoryPassage(@" 3.5", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"You and me both, buddy. So what are we here for?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"There's something below the orphanage that you need to see.\" ", "4", null);
		yield break;
	}


	// .............
	// #5: 4

	void passage5_Init()
	{
		this.Passages[@"4"] = new StoryPassage(@"4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"I'll be damned...Come on, let's hurry up. The night is no time to be out and about.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Lead him to the laboratory. ", " EndDia", null);
		yield break;
	}


	// .............
	// #6:  EndDia

	void passage6_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		macros3.ChangeScene("Exp3_Facillity_Hall");
		yield break;
	}


}