/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageEightTwo.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageEightTwo: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageEightTwo()
	{
		this.StartPassage = "Laboratory with Sheriff";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Laboratory with Sheriff

	void passage1_Init()
	{
		this.Passages[@"Laboratory with Sheriff"] = new StoryPassage(@"Laboratory with Sheriff", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros3.SetSpeaker("Sheriff");
		yield return lineBreak();
		yield return text("\"My god...Who would have thought all this was down here?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Any idea what this place is for?\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"I'm not known for my imagination, but if I had a good imagination I'd say this is some kind of lab for science experiments, and probably not the ethical kind.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I found some empty bottles and syrginges.\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Interesting,\" the sheriff says as he takes another look around. He picks up the copy of \"Arctic Lightning,\" and then shakes his head.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Such a violent movie,\" he mumbles. \"No wonder these kids are like savages.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You know, one of the kids survived the fire. His name is George, and he seems like an okay boy.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"George, you say? I've heard the name before, but never in the same sentence as 'nice'.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What do you mean?\"", " 5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"He's crazy,\" the sheriff says. \"Used to get into fights all the time with the other kids, regularly drinks and does drugs...Some lady even claims he strangled her cat with his bare hands.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Mention the animal bones outside the orphanage. ", " 6", null);
		yield break;
	}


	// .............
	// #6:  6

	void passage6_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"As strange as that is, I'm not surprised...Weird things go on at this orphanage.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I found this file when I came here last night, but I haven't had the chance to look over it yet. Shall we?\" ", " 7", null);
		yield break;
	}


	// .............
	// #7:  7

	void passage7_Init()
	{
		this.Passages[@" 7"] = new StoryPassage(@" 7", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Let's see it.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Take out the file and read it. ", " 8", null);
		yield break;
	}


	// .............
	// #8:  8

	void passage8_Init()
	{
		this.Passages[@" 8"] = new StoryPassage(@" 8", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"...Human experimentation...Exposure to violence...Project Firework? What in the hell is this?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"It seems like someone has been conducting experiments on your town's orphans for some time. But why?\" ", " 9", null);
		yield break;
	}


	// .............
	// #9:  9

	void passage9_Init()
	{
		this.Passages[@" 9"] = new StoryPassage(@" 9", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"Not sure. I can barely make sense of this paper. Too much government lingo.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"But if it's government lingo...\" ", " 10", null);
		yield break;
	}


	// .............
	// #10:  10

	void passage10_Init()
	{
		this.Passages[@" 10"] = new StoryPassage(@" 10", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"Let's not jump to conclusions. We wouldn't want to cross those men in black now, would we?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Smart plan. For now, let's try to find some more documents.\" ", " 11", null);
		yield break;
	}


	// .............
	// #11:  11

	void passage11_Init()
	{
		this.Passages[@" 11"] = new StoryPassage(@" 11", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		macros3.SetSpeaker(" ");
		yield return lineBreak();
		yield return text("You and the sheriff search through the filing cabinets and drawers, eventually scrapping together a small stack of papers.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Read \"Methods\". ", " 12", null);
		yield return lineBreak();
		yield return link("Read \"Lead Scientist's Log\". ", " 12.3", null);
		yield return lineBreak();
		yield return link("Read \"Subjects (Recently Updated)\". ", " 12.2", null);
		yield return lineBreak();
		yield return link("Finish reading. ", " 13", null);
		yield break;
	}


	// .............
	// #12:  12

	void passage12_Init()
	{
		this.Passages[@" 12"] = new StoryPassage(@" 12", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Methods");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Level A: Negative Reinforcement");
		yield return lineBreak();
		yield return text("- Punish and prevent disruptive behavior, with physical force if appropriate.");
		yield return lineBreak();
		yield return text("- Confiscate personal possessions at random times,in order to aggravate subjects.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.1", null);
		yield break;
	}


	// .............
	// #13:  12.2

	void passage13_Init()
	{
		this.Passages[@" 12.2"] = new StoryPassage(@" 12.2", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Subjects (Recently Updated)");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("ID Number: 038");
		yield return lineBreak();
		yield return text("Sex: Male");
		yield return lineBreak();
		yield return text("Age: 12");
		yield return lineBreak();
		yield return text("Notes: Subject shows consistent disobedience and disdain for authority members. Force necessary in multiple situations. Recommended for placement in advanced program.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.21", null);
		yield break;
	}


	// .............
	// #14:  12.3

	void passage14_Init()
	{
		this.Passages[@" 12.3"] = new StoryPassage(@" 12.3", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Log: 4:45 PM, 11/8");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Treatment continues to proceed as planned. Despite the lack of major developments researchers note behavorial changes in the subjects, most notably an increase in aggression. With luck, a more satisfactory result with be achieved in Phase 2.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.31", null);
		yield break;
	}


	// .............
	// #15:  12.1

	void passage15_Init()
	{
		this.Passages[@" 12.1"] = new StoryPassage(@" 12.1", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Level B: Habituation");
		yield return lineBreak();
		yield return text("- Expose subjects to violent film, in order to desensitize subjects.");
		yield return lineBreak();
		yield return text("- Gradually introduce and normalize the harm of animals to the subjects.");
		yield return lineBreak();
		yield return text("- Encourage disputes between subjects.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.11", null);
		yield break;
	}


	// .............
	// #16:  12.11

	void passage16_Init()
	{
		this.Passages[@" 12.11"] = new StoryPassage(@" 12.11", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Level C: Escalation");
		yield return lineBreak();
		yield return text("- Introduce regular drug use to subjects; continue with exposure to violent film and animal abuse.");
		yield return lineBreak();
		yield return text("- ???");
		yield return lineBreak();
		yield return text("- ???");
		yield return lineBreak();
		yield return text("- ???");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The list appears to be unfinished.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to documents. ", " 11", null);
		yield break;
	}


	// .............
	// #17:  13

	void passage17_Init()
	{
		this.Passages[@" 13"] = new StoryPassage(@" 13", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		macros3.SetSpeaker("Sheriff");
		yield return lineBreak();
		yield return text("\"My god...This...This is vile!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"We have to tell someone about this.\" ", " 14", null);
		yield break;
	}


	// .............
	// #18:  12.21

	void passage18_Init()
	{
		this.Passages[@" 12.21"] = new StoryPassage(@" 12.21", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("ID Number: 022");
		yield return lineBreak();
		yield return text("Sex: Male");
		yield return lineBreak();
		yield return text("Age: 15");
		yield return lineBreak();
		yield return text("Notes: Model subject. Complies with treatments with little resistance, almost willingly at times. Difficulty with socialization.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.22", null);
		yield break;
	}


	// .............
	// #19:  12.22

	void passage19_Init()
	{
		this.Passages[@" 12.22"] = new StoryPassage(@" 12.22", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("ID Number: 002");
		yield return lineBreak();
		yield return text("Sex: Female");
		yield return lineBreak();
		yield return text("Age: 16(?)");
		yield return lineBreak();
		yield return text("Notes: Highly dangerous to staff and peers. Known to craft and hide weapons from household materials. Has severely injured other subjects on multiple occasions.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to documents. ", " 11", null);
		yield break;
	}


	// .............
	// #20:  12.31

	void passage20_Init()
	{
		this.Passages[@" 12.31"] = new StoryPassage(@" 12.31", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Log: 6:30 AM, 11/30");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("During the night, multiple staff were injured in an altercation involving Subject 022 and multiple other subjects. Subject displayed extreme aggression and agitation. The situation has further isolated Subject 022 from his peers.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Note: HQ has requested Subject 002 be observed and considered for potential use in the future.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Next ", " 12.32", null);
		yield break;
	}


	// .............
	// #21:  12.32

	void passage21_Init()
	{
		this.Passages[@" 12.32"] = new StoryPassage(@" 12.32", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Log: 2:00 PM, 12/1");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("A fire was started in the facility today. Staff managed to extinguish it, but the perpetrator is unknown. All matches and lighters have been confinscated from subjects. Subjects and staff alike regularly show unease and anxiety.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to documents. ", " 11", null);
		yield break;
	}


	// .............
	// #22:  14

	void passage22_Init()
	{
		this.Passages[@" 14"] = new StoryPassage(@" 14", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("\"Right...But we need to be careful. You head back to the inn and stay low. I'll go to my office and phone this in. Come meet me in an hour.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Stay safe, sheriff.\" ", " 15", null);
		yield break;
	}


	// .............
	// #23:  15

	void passage23_Init()
	{
		this.Passages[@" 15"] = new StoryPassage(@" 15", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("\"You as well, detective. Just what in the hell have we found here...?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield break;
	}


	// .............
	// #24:  EndDia

	void passage24_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		macros3.ChangeScene("Exp4_Inn");
		yield break;
	}


}