/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageFour.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageFour: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageFour()
	{
		this.StartPassage = "Protagonist at Orphanage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Protagonist at Orphanage

	void passage1_Init()
	{
		this.Passages[@"Protagonist at Orphanage"] = new StoryPassage(@"Protagonist at Orphanage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("You arrive at the front of the orphanage that night and take a look around. There isn't anyone else nearby.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Go into the building. ", " 2", null);
		yield return lineBreak();
		yield return link("Look around outside. ", " 2.5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		macros3.ChangeScene("Exp_Orphanage_Hall");
		yield break;
	}


	// .............
	// #3:  2.5

	void passage3_Init()
	{
		this.Passages[@" 2.5"] = new StoryPassage(@" 2.5", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("You observe your surroundings in front of the burned orphanage. The yard is bare of greenery save some patchy grass. Next to your feet, there are bits of broken glass and animal bones.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Go into the building. ", " 2", null);
		yield break;
	}


}