/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageNine.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageNine: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageNine()
	{
		this.StartPassage = "Inn with innkeeper";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Inn with innkeeper

	void passage1_Init()
	{
		this.Passages[@"Inn with innkeeper"] = new StoryPassage(@"Inn with innkeeper", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"You...! Come here, and don't talk too loud.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's going on?\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("The innkeeper's eyes dart around the room. She's clearly nervous.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Two men came by looking for you. I told them I didn't know so they let me go, but...I think they're out to get you, detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks for the warning.\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"One more thing...The men were looking for that orphan as well. He hasn't been back in a while. I hope they didn't do something to him...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'll make sure he's safe.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"That's a relief. I think you should go find the sheriff and make sure he's updated.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Will do.\" ", " EndDia", null);
		yield break;
	}


	// .............
	// #5:  EndDia

	void passage5_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		macros3.EndDialogue(" ");
		yield break;
	}


}