/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageFourTwo.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageFourTwo: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@OrphanageFourTwo()
	{
		this.StartPassage = "2";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: 2

	void passage1_Init()
	{
		this.Passages[@"2"] = new StoryPassage(@"2", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("After working up the nerve to step into the burned and possibly unstable building, you enter into what's left of the orphanage. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The inside of the orphanage is no nicer than the outside, with almost every wooden surface charred black. You see what looks to be destroyed furniture and glassware scattered around.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Check the room on the left. ", " 3", null);
		yield return lineBreak();
		yield return link("Check the room on the right. ", " 3.5", null);
		yield break;
	}


	// .............
	// #2:  3

	void passage2_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You peek your head into the room, but there's nothing besides ash and cobwebs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Check the other room. ", " 3.5", null);
		yield break;
	}


	// .............
	// #3:  3.5

	void passage3_Init()
	{
		this.Passages[@" 3.5"] = new StoryPassage(@" 3.5", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("The room is empty, or seems to be until you notice something under a broken floorboard. You bend down and pick it up. It's a small doll of a girl with braids, accessories and everything included. You decide to leave it where you found it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Keep exploring. ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Back in the hallway, you take a peek around. There are three closed doors further down the hallway, apparently spared from the fire's wrath.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Check the first door. ", " 5", null);
		yield return lineBreak();
		yield return link("Check the second door. ", " 5.1", null);
		yield return lineBreak();
		yield return link("Check the third door. ", " 5.2", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("The door only leads you to a closet, which is eerily empty of both ash and possessions. On the ground and on the inside of the door, there are what seem to be...claw marks?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to the hallway. ", " 4", null);
		yield break;
	}


	// .............
	// #6:  5.1

	void passage6_Init()
	{
		this.Passages[@" 5.1"] = new StoryPassage(@" 5.1", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("You open the door and step into a room that barely qualifies as a kitchen, given its small dimensions. Blackened pots and pans sit on what remains of the shelves and counter.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to the hallway. ", " 4", null);
		yield break;
	}


	// .............
	// #7:  5.2

	void passage7_Init()
	{
		this.Passages[@" 5.2"] = new StoryPassage(@" 5.2", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("The door is locked.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to the hallway. ", " 4", null);
		yield return lineBreak();
		yield return link("Break down the door. ", " 6", null);
		yield break;
	}


	// .............
	// #8:  6

	void passage8_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Sure enough, with a hard push the door caves in, most likely weakened by the fire. In front of you lies a narrow staircase leading down. It's dark.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Take out a flashlight and continue on. ", "EndDia", null);
		yield break;
	}


	// .............
	// #9: EndDia

	void passage9_Init()
	{
		this.Passages[@"EndDia"] = new StoryPassage(@"EndDia", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		macros2.EndDialogue(" ");
		yield break;
	}


}