/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageOne.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageOne: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@OrphanageOne()
	{
		this.StartPassage = "Diner with Waitress";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Diner with Waitress

	void passage1_Init()
	{
		this.Passages[@"Diner with Waitress"] = new StoryPassage(@"Diner with Waitress", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Hey there,\" Linda says with sly smile. \"I thought we'd see you back soon. What will it be today, hon?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"An omelette and a cup of coffee, please.\" ", " 2", null);
		yield return lineBreak();
		yield return link("\"No time to eat. I actually came by to ask some questions, if you don't mind.\" ", " 2.5", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Coming right up. Anything else on your mind? Maybe not food-related?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Actually, I did have some questions...\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  2.5

	void passage3_Init()
	{
		this.Passages[@" 2.5"] = new StoryPassage(@" 2.5", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Well look at you, a man on a mission! I'll do my best to help you, but no guarantees.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Have you heard anything about some government guys staying around town? Kinda tall, wearing black suits?\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  3

	void passage4_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"What's on your mind?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Have you heard anything about some government guys staying in town? Kinda tall, wearing black suits?\" ", " 4", null);
		yield break;
	}


	// .............
	// #5:  4

	void passage5_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Linda looks at you for a moment, and then bites her lip.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Sounds a bit familiar...Let me see...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"They might have said they were insurance agents. And they also checked out the orphanage after it burned down, if that helps jog your memory.\" ", " 5", null);
		yield break;
	}


	// .............
	// #6:  5

	void passage6_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"Oh!\" she exclaims, suddenly excited. \"I think I did serve two men like that once or twice, a few weeks back. Haven't seen them since, but they seemed decent enough. Quiet, if anything.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You didn't happen to overhear anything they were talking about, did you? \" ", " 6", null);
		yield break;
	}


	// .............
	// #7:  6

	void passage7_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Maybe I did, and maybe I didn't,\" Linda smiles. \"But should I tell you? What if you're actually a foreign spy, and I'm helping you steal government secrets?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You know you can trust me. I just want to make sure these guys are legit.\" ", " 7", null);
		yield return lineBreak();
		yield return link("\"Quit messing around, this is serious.\" ", " 7.5", null);
		yield break;
	}


	// .............
	// #8:  7

	void passage8_Init()
	{
		this.Passages[@" 7"] = new StoryPassage(@" 7", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Now that you mention it...something seemed a little off about those two. They felt a little out of place in a small town like ours, driving fancy black cars with tinted windows around...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What else?\" ", " 8", null);
		yield break;
	}


	// .............
	// #9:  7.5

	void passage9_Init()
	{
		this.Passages[@" 7.5"] = new StoryPassage(@" 7.5", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"It's just a joke,\" Linda pouts. \"Not everything has to be gloom and doom, you know? But now that you mention it...something felt off about those two. They gave me a weird feeling that I couldn't shake even after they left the diner.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What else?\" ", " 8", null);
		yield break;
	}


	// .............
	// #10:  8

	void passage10_Init()
	{
		this.Passages[@" 8"] = new StoryPassage(@" 8", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"Well...What if I told you I eavesdropped on them for just a few seconds?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I would say, fill me in on the details.\" ", " 9", null);
		yield break;
	}


	// .............
	// #11:  9

	void passage11_Init()
	{
		this.Passages[@" 9"] = new StoryPassage(@" 9", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("\"I can't do much in the way of details, but I did overhear them saying one phrase over and over again. Under the orphanage.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Under the orphanage? You don't think...\" ", " 10", null);
		yield break;
	}


	// .............
	// #12:  10

	void passage12_Init()
	{
		this.Passages[@" 10"] = new StoryPassage(@" 10", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"Do I think there's something under the orphanage? Maybe. Am I going to go check? Hell no. That's your job, detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I guess I know where I'm headed next. Thanks for the tip.\" ", " 11", null);
		yield break;
	}


	// .............
	// #13:  11

	void passage13_Init()
	{
		this.Passages[@" 11"] = new StoryPassage(@" 11", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"No problem, hon,\" Linda says. \"Oh, one more thing. There may have been a survivor from the orphanage fire after all, or so I hear.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"A survivor? I'd love to talk with them for my investigation. Do you know who they are and where they're staying?\" ", " 12", null);
		yield break;
	}


	// .............
	// #14:  12

	void passage14_Init()
	{
		this.Passages[@" 12"] = new StoryPassage(@" 12", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("\"You ask a lot of questions,\" Linda chuckles. \"I suppose that's a prequisite for the job though. Don't know his name or what he looks like, but he's staying at the town inn.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That's where I'm staying.\" ", " 13", null);
		yield break;
	}


	// .............
	// #15:  13

	void passage15_Init()
	{
		this.Passages[@" 13"] = new StoryPassage(@" 13", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\"So you should have noticed him hanging around, unless you're really that bad at your job.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Very funny. Thanks for everything, Linda. I'll take the check, please.\" ", " 14", null);
		yield break;
	}


	// .............
	// #16:  14

	void passage16_Init()
	{
		this.Passages[@" 14"] = new StoryPassage(@" 14", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\"Come by anytime you need something,\" Linda says with a wink.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield break;
	}


	// .............
	// #17:  EndDia

	void passage17_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		macros2.EndDialogue(" ");
		yield break;
	}


}