/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageSeven.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageSeven: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageSeven()
	{
		this.StartPassage = "Diner with Waitress";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Diner with Waitress

	void passage1_Init()
	{
		this.Passages[@"Diner with Waitress"] = new StoryPassage(@"Diner with Waitress", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Hey, do you see him? Over there?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Who? The orphan?\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"No, the president of the United States...Yes, the orphan! I've never seen him out and about like this.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You're awfully excited about this.\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"I'm excited for you,\" Linda says with a smirk. \"I think this is a good chance for you to talk to him. Word has it that he's a shy one, but I believe in you.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I already tried this, but I guess I can give it another go.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Go for it. And give me the details afterwards. I'm pretty curious about this boy...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield return lineBreak();
		yield return link("\"By the way...\" ", " 5", null);
		yield break;
	}


	// .............
	// #5:  EndDia

	void passage5_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		macros3.EndDialogue(" ");
		yield break;
	}


	// .............
	// #6:  5

	void passage6_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"What's on your mind?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Have you ever heard about the orphans...hurting animals?\" ", " 6", null);
		yield return lineBreak();
		yield return link("\"Do you know if anyone at the orphanage was heavy drinker or into drugs?\" ", " 6.1", null);
		yield return lineBreak();
		yield return link("\"Those government guys tried to scare me off this morning.\" ", " 6.2", null);
		yield break;
	}


	// .............
	// #7:  6

	void passage7_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Goodness, that sounds awful! But...it makes sense if I think about it. Pets go missing a little too easily in this town for it to be a coincidence.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks for the info, Linda.\" ", " 7", null);
		yield break;
	}


	// .............
	// #8:  6.1

	void passage8_Init()
	{
		this.Passages[@" 6.1"] = new StoryPassage(@" 6.1", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"I'm not 100% on this, but some of those kids looked like they were really struggling with drugs and alcohol, wandering around midday drunk and all...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks for the info, Linda.\" ", " 7", null);
		yield break;
	}


	// .............
	// #9:  6.2

	void passage9_Init()
	{
		this.Passages[@" 6.2"] = new StoryPassage(@" 6.2", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"That sounds scary! Be careful, hon. I might get lonely if get don't come back.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks, Linda. ", " 7", null);
		yield break;
	}


	// .............
	// #10:  7

	void passage10_Init()
	{
		this.Passages[@" 7"] = new StoryPassage(@" 7", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"Anytime,\" Linda winks.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", "  EndDia", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11:   EndDia

	void passage11_Init()
	{
		this.Passages[@"  EndDia"] = new StoryPassage(@"  EndDia", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		macros3.EndDialogue(" ");
		yield break;
	}


}