/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageThree.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageThree: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@OrphanageThree()
	{
		this.StartPassage = "Innkeeper at Inn";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Innkeeper at Inn

	void passage1_Init()
	{
		this.Passages[@"Innkeeper at Inn"] = new StoryPassage(@"Innkeeper at Inn", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"I heard you talking to the boy,\" the innkeeper says. \"He's a quiet one, but nice enough.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You've been letting him stay here since the fire?\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Mhmm,\" she nods. \"It's only right to give people a hand up when they've been pushed into the dirt, isn't it?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Has he told you anything about his time at the orphanage? He wasn't exactly keen on sharing with me...\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"He's hardly said a word to me,\" the innkeeper frowns. \"Teenage boys already have trouble communicating, but I feel like he's on a different level.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What do you mean?\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"He's basically a recluse. Hardly ever leaves the inn. Just sits in his room and reads all day. I know he's been through a lot, but you can't just let yourself shut down like that.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Been through a lot?\" ", " 5", null);
		yield return lineBreak();
		yield return link("\"Does he have any friends or family?\" ", " 5.5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"The orphanage was built with good intentions, but it wasn't as well run as it could have been. I swear to you, I used to see some of those kids walk by, bruises on their arms and legs as bright as day.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That's horrible. Did anyone ever do something about it, like go to the sheriff?\" ", " 6", null);
		yield break;
	}


	// .............
	// #6:  5.5

	void passage6_Init()
	{
		this.Passages[@" 5.5"] = new StoryPassage(@" 5.5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"As far as I can tell he's on his own, and has been for a while.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That's a real shame. What can you tell me about the orphanage he came from? The one that burned down?\" ", " 5", null);
		yield break;
	}


	// .............
	// #7:  6

	void passage7_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Not that I know of,\" says the innkeeper. \"To be honest, this town wasn't very kind towards those poor kids. Children and adults alike made a game of picking on them. But hey, that's just how the dice fall sometimes.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Okay. Thanks for the info.\" Leave. ", " EndDia", null);
		yield return lineBreak();
		yield return link("\"That's not very empathetic, is it?\" ", " 7.5", null);
		yield break;
	}


	// .............
	// #8:  EndDia

	void passage8_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		macros2.EndDialogue(" ");
		yield break;
	}


	// .............
	// #9:  7.5

	void passage9_Init()
	{
		this.Passages[@" 7.5"] = new StoryPassage(@" 7.5", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"It's not like I'm hosting one of those kids for free or anything...\" the innkeeper grumbles.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield break;
	}


}