/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageEleven.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageEleven: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageEleven()
	{
		this.StartPassage = "Outside orphanage with mib";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Outside orphanage with mib

	void passage1_Init()
	{
		this.Passages[@"Outside orphanage with mib"] = new StoryPassage(@"Outside orphanage with mib", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Hey you, stop right there!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("In a flash, both men have pistols raised at you.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Put your hands up. ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("One of the men pats you down, and then nods to his companion,");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"No guns, detective?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'm an insurance detective, not a cop. But just who are you guys?\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Funny...The sheriff asked the same question.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"The sheriff? Where is he?\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Before your question can be answered, the men suddenly turn back towards the orphanage, alarmed.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I think I saw a light inside!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Cuff him to the fence. We'll take care of him after.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("They restrain your arm to a nearby fence and run off into the orphanage with their guns drawn. You're alone now.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Look for ways to escape. ", " 5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("In their haste, the men hadn't noticed that the fence they handcuffed you to wasn't actually a closed loop. If you could reach high enough, you could slip your arm over and free yourself.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("On the other hand, trying to escape from mysterious armed men wasn't the best idea when they could be back at any minute. You could also just wait.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Try to escape. ", " 6", null);
		yield return lineBreak();
		yield return link("Wait. ", " 5", null);
		yield break;
	}


	// .............
	// #6:  6

	void passage6_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("After some time and effort, you manage to jump up and get your arm over the top of the fence. Now free, you look towards the orphanage and make up your mind. There was only one person that light could have been: George, the orphan. What he was there for...You don't want to think about that.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Enter the orphanage. ", " EndDia", null);
		yield break;
	}


	// .............
	// #7:  EndDia

	void passage7_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros3.ChangeScene("Exp5_Facillity");
		yield break;
	}


}