/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageThirteen.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageThirteen: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageThirteen()
	{
		this.StartPassage = "Diner with Waitress";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Diner with Waitress

	void passage1_Init()
	{
		this.Passages[@"Diner with Waitress"] = new StoryPassage(@"Diner with Waitress", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros3.SetSpeaker("Linda");
		yield return lineBreak();
		yield return text("\"Well I");
		yield return text("''");
		yield return text("ll be damned. If it isn't the town's hero-detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Hey, Linda. Just a cup of joe today.\" ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Coming right up. You've made some headlines, you know, exposing the nasty business in this town.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"All part of a day's work.\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Linda flashes you a smile.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"And I guess you've got many days work ahead of you, seeing as you're the new sheriff in town.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Acting sheriff, and only until they find a replacement.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Regardless, the whole town and I really appreciate what you've done. On another note,  whatever happened to that boy, George?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'm not sure. Once we left the orphanage, he just took off without a word. Could be anywhere by now.\" ", " 5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"Bless his heart. I hope he manages to clean himself up.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I believe in him.\" ", " 6", null);
		yield break;
	}


	// .............
	// #6:  6

	void passage6_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"I'm not sure I believe in him, but I know I believe in you,\" Linda says with a wink. \"So if you have faith, that's good enough for me. Oh, I almost forgot! Here's you coffee.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("With a quick swish, Linda fills up your mug.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Good work, detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Finish ", " EndDia", null);
		yield break;
	}


	// .............
	// #7:  EndDia

	void passage7_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros3.ChangeScene("Credits");
		yield break;
	}


}