/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageFourThree.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageFourThree: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@OrphanageFourThree()
	{
		this.StartPassage = "Under the Orphanage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Under the Orphanage

	void passage1_Init()
	{
		this.Passages[@"Under the Orphanage"] = new StoryPassage(@"Under the Orphanage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Flashlight in hand, you descend down into the darkness. The wooden floors and walls give way to metal panels. Strange. Not what one would expect below an orphanage.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Continue on. ", " 2", null);
		yield break;
	}


	// .............
	// #2:  2

	void passage2_Init()
	{
		this.Passages[@" 2"] = new StoryPassage(@" 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You eventually reach a large room. In the little light you have, you can see burned papers and ashes scattered around, evidence that even this hidden area couldn't be saved from the fire.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Look around the floor. ", " 3", null);
		yield return lineBreak();
		yield return link("Look around the cabinets and drawers. ", " 3.5", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Getting low and peering around, you find little but papers burned beyond readability and ashes. The strange layout of the room starts to capture your attention, however. It almost seems like...some sort of laboratory.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Search the cabinets and drawers. ", " 3.5", null);
		yield break;
	}


	// .............
	// #4:  3.5

	void passage4_Init()
	{
		this.Passages[@" 3.5"] = new StoryPassage(@" 3.5", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("In the first cabinet you open, you find...a dozen empty beer bottles?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("In the next cabinet, you find a few syringes that look like thy've been used.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("In a nearby drawer, you find a copy of the movie \"Arctic Lightning\", a popular war/action movie.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Keep searching. ", " 4", null);
		yield break;
	}


	// .............
	// #5:  4

	void passage5_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("One filing cabinet is particularly hard to open, so you give it a hard pull. It budges, but doesn't open. You pull again, this time harder, and it snaps open with a loud thud.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Inside, there's a lone manila folder containing a single paper.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Take the file. ", " 5", null);
		yield break;
	}


	// .............
	// #6:  5

	void passage6_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("As you take the file, you hear something creak behind you. You quickly turn, but there's nothing there. Convincing yourself it was just the house settling but still unnerved, you head back for the first floor of the orphanage, file in hand. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("A hidden laboratory beneath the orphanage was certainly a major discovery, though. You definitely need to tell the sheriff about this, and the file too...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield break;
	}


	// .............
	// #7:  EndDia

	void passage7_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros3.ChangeScene("Exp2_OverworldMenuSelect");
		yield break;
	}


}