/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: OrphanageSixTwo.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @OrphanageSixTwo: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@OrphanageSixTwo()
	{
		this.StartPassage = "Government Guys in Office";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Government Guys in Office

	void passage1_Init()
	{
		this.Passages[@"Government Guys in Office"] = new StoryPassage(@"Government Guys in Office", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros2.SetSpeaker("Government Men(?)");
		yield return lineBreak();
		yield return text("\"You're the insurance detective that's been snooping around for the last few days?\" asks one of the men, in a low voice. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Yes, that's me. Can I ask what's going on here?\" ", " 3", null);
		yield return lineBreak();
		yield return link("\"Sorry, wrong number.\" ", " 2.5", null);
		yield break;
	}


	// .............
	// #2:  2.5

	void passage2_Init()
	{
		this.Passages[@" 2.5"] = new StoryPassage(@" 2.5", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"I don't appreciate the sarcasm. We're here on important business, and if you aren't cooperating you're just getting in our way.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"May I at least know what this important business is?\" ", " 3", null);
		yield break;
	}


	// .............
	// #3:  3

	void passage3_Init()
	{
		this.Passages[@" 3"] = new StoryPassage(@" 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"We'll be asking the questions, detective. I hear from our pal here, the sheriff, that you've visited the orphanage quite recently. What did you find?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Nothing interesting.\" ", " 4", null);
		yield return lineBreak();
		yield return link("\"Ash and cinders.\" ", " 4", null);
		yield return lineBreak();
		yield return link("\"A burned down orphanage.\" ", " 4", null);
		yield break;
	}


	// .............
	// #4:  4

	void passage4_Init()
	{
		this.Passages[@" 4"] = new StoryPassage(@" 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Is that so? Nothing of note to mention?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Nope.\" ", " 5", null);
		yield break;
	}


	// .............
	// #5:  5

	void passage5_Init()
	{
		this.Passages[@" 5"] = new StoryPassage(@" 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"...Very well. Carry on with your investigation, but stay out of our way.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'm still not sure what I'd be getting in the way of...\" ", " 6", null);
		yield return lineBreak();
		yield return link("\"Yes sir.\" ", " 6", null);
		yield break;
	}


	// .............
	// #6:  6

	void passage6_Init()
	{
		this.Passages[@" 6"] = new StoryPassage(@" 6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("The two men don't seem to hear you, and start quietly talking amongst themselves. You give the sheriff a quick glance, and he nods in response.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Leave. ", " EndDia", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7:  EndDia

	void passage7_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros2.EndDialogue(" ");
		yield break;
	}


}