/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Beginning.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Beginning: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@Beginning()
	{
		this.StartPassage = "Beginning";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Beginning

	void passage1_Init()
	{
		this.Passages[@"Beginning"] = new StoryPassage(@"Beginning", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("Phone rings *ring ring ring* ", "The call", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #2: The call

	void passage2_Init()
	{
		this.Passages[@"The call"] = new StoryPassage(@"The call", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return link("Mysterious Girl: There has been a fire in my town. It destroyed the majority of the town, and it would be nice if you come to figure it out. Detective: May I ask who I am speaking to?", "Convo 1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #3: Convo 1

	void passage3_Init()
	{
		this.Passages[@"Convo 1"] = new StoryPassage(@"Convo 1", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return link("Mysterious Girl: I will send you the location through mail. Please come as soon as possible. You will be paid fortune! *hangs up*", "Mysterious Girl: I will send you the location through mail. Please come as soon as possible. You will be paid fortune! *hangs up*", null);
		yield break;
	}


	// .............
	// #4: Mysterious Girl: I will send you the location through mail. Please come as soon as possible. You will be paid fortune! *hangs up*

	void passage4_Init()
	{
		this.Passages[@"Mysterious Girl: I will send you the location through mail. Please come as soon as possible. You will be paid fortune! *hangs up*"] = new StoryPassage(@"Mysterious Girl: I will send you the location through mail. Please come as soon as possible. You will be paid fortune! *hangs up*", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}