/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Billy_Joel.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Billy_Joel: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@Billy_Joel()
	{
		this.StartPassage = "Denial";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Denial

	void passage1_Init()
	{
		this.Passages[@"Denial"] = new StoryPassage(@"Denial", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"I'm telling you, man, we didn't start the fire!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Then who did?\"", "No one", null);
		yield return lineBreak();
		yield return link("\"I don't believe you. Where were you at 9 o'clock last Saturday?\" ", "AttheBar", null);
		yield break;
	}


	// .............
	// #2: No one

	void passage2_Init()
	{
		this.Passages[@"No one"] = new StoryPassage(@"No one", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"No one! It was always burning, since the world's been turning!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I find that improbable.\"", "It's the truth.", null);
		yield break;
	}


	// .............
	// #3: It's the truth.

	void passage3_Init()
	{
		this.Passages[@"It's the truth."] = new StoryPassage(@"It's the truth.", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"It's the truth.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I think you're crazy\"", "Maybe", null);
		yield break;
	}


	// .............
	// #4: Maybe

	void passage4_Init()
	{
		this.Passages[@"Maybe"] = new StoryPassage(@"Maybe", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"You may be right. But I'm not the lunatic you're looking for.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I don't believe you. Where were you at 9 o'clock last Saturday?\" ", "AttheBar", null);
		yield break;
	}


	// .............
	// #5: AttheBar

	void passage5_Init()
	{
		this.Passages[@"AttheBar"] = new StoryPassage(@"AttheBar", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"I was at the bar, playing the piano, I swear! Ask any of my friend John. He was buying my drinks all night.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"John no longer lives in the area. He packed his bags, sold the house and bought a ticket to the West Coast. Wants to be a movie star, apparently.\"", "Good", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Good

	void passage6_Init()
	{
		this.Passages[@"Good"] = new StoryPassage(@"Good", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"I'm happy to see that he's going ahead with his own life. Now leave me alone! You have no proof.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You seem in a hurry to get out of town\"", "Can't Stay", null);
		yield break;
	}


	// .............
	// #7: Can't Stay

	void passage7_Init()
	{
		this.Passages[@"Can't Stay"] = new StoryPassage(@"Can't Stay", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"I just can't stay another day, or I won't be here in another year if I don't stay on the charts.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's that supposed to mean?\"", "PREASSURE", null);
		yield break;
	}


	// .............
	// #8: PREASSURE

	void passage8_Init()
	{
		this.Passages[@"PREASSURE"] = new StoryPassage(@"PREASSURE", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Oh, I'll tell you what it means. I can't take this preassure.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Billy Joel moves out.");
		yield return lineBreak();
		yield return lineBreak();
		macros2.EndDialogue("Come now, Virginia!");
		yield break;
	}


}