/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: DinerScene.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @DinerScene: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@DinerScene()
	{
		this.StartPassage = "Enter the Diner";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Enter the Diner

	void passage1_Init()
	{
		this.Passages[@"Enter the Diner"] = new StoryPassage(@"Enter the Diner", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("On the sheriff's suggestion, you decide to stop for a bite to eat at the diner across the street. You can't go wrong with a cup of coffee, and the chance to pick up some juicy gossip was just what this investigator ordered.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Enter the diner. ", " Diner 1.5", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Diner 2

	void passage2_Init()
	{
		this.Passages[@" Diner 2"] = new StoryPassage(@" Diner 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Alright,\" she grins as she jots your order down. \"A burger and a coffee for the bigshot detective from the city.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"How did you know...?\" ", " Diner 3", null);
		yield break;
	}


	// .............
	// #3:  Diner 3

	void passage3_Init()
	{
		this.Passages[@" Diner 3"] = new StoryPassage(@" Diner 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Word travels fast in this town,\" she says, \"and when you're waiting tables you overhear things. Affairs, scandals, detectives visiting from out of town...you hear it all.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Interesting. Say, err...\" ", " Diner 4", null);
		yield break;
	}


	// .............
	// #4:  Diner 4

	void passage4_Init()
	{
		this.Passages[@" Diner 4"] = new StoryPassage(@" Diner 4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Linda,\" she smiles. \"You can call me Linda.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Say, Linda...I'm investigating the fire from a few months ago. Have you heard any rumors about that?\" ", " Diner 5", null);
		yield break;
	}


	// .............
	// #5:  Diner 5

	void passage5_Init()
	{
		this.Passages[@" Diner 5"] = new StoryPassage(@" Diner 5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"The fire, huh? I reckon I've heard a whisper or two about it, but nothing I can be sure about.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("She puts a hand on her chin and stops to think.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait for her politely. ", " Diner 5.5", null);
		yield break;
	}


	// .............
	// #6: Dolls Lead

	void passage6_Init()
	{
		this.Passages[@"Dolls Lead"] = new StoryPassage(@"Dolls Lead", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Linda has a somber expression on her face.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"The parents were really devastated,\" she says. \"Still are, too. They're staying at the new church, the nice and renovated one, and they're always praying...Breaks your heart, really.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"So their kid was alone when the fire started?\" ", " Dolls 2", null);
		yield break;
	}


	// .............
	// #7: Old Man Lead

	void passage7_Init()
	{
		this.Passages[@"Old Man Lead"] = new StoryPassage(@"Old Man Lead", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"You must mean Old Gary,\" Linda says. \"Bit of a grouch, he is. But that don't make what those kids did any better. Trespassing, arson...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Are you saying some college kids really burned down the church?\" ", " Old Man Lead 2", null);
		yield break;
	}


	// .............
	// #8:  Orphanage Lead

	void passage8_Init()
	{
		this.Passages[@" Orphanage Lead"] = new StoryPassage(@" Orphanage Lead", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Oh, it's no surprise that the townsfolk are chattering about that,\" Linda says with a swagger. \"Damn shame what happened! The entire orphanage burned to the ground, and not a single survivor found long after the flames had gone out.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("She crosses her heart, and looks somber for a moment.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait for her to continue. ", " Orphan 1.5", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9:  Dolls 2

	void passage9_Init()
	{
		this.Passages[@" Dolls 2"] = new StoryPassage(@" Dolls 2", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Linda purses her lips.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Yes, that's what they said, but...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"But...?\" ", " Dolls 3", null);
		yield break;
	}


	// .............
	// #10:  Dolls 3

	void passage10_Init()
	{
		this.Passages[@" Dolls 3"] = new StoryPassage(@" Dolls 3", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"All I'm saying is, it might not have been the fire that killed that little girl,\" she says hesitantly. \"For whatever reason, bad things just seem to happen to kids in this town.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"So something similar has happened before?\" ", " Dolls 4", null);
		yield break;
	}


	// .............
	// #11:  Dolls 4

	void passage11_Init()
	{
		this.Passages[@" Dolls 4"] = new StoryPassage(@" Dolls 4", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("\"Sorry dear,\" she says with a frown. \"I ain't gonna talk about it any more...bad mojo, it is. But if you're really curious, why don't you try talking to the parents yourself?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Not a bad idea. Maybe I'll drop by the church tomorrow with some questions.\" ", " End 3", null);
		yield break;
	}


	// .............
	// #12:  End 3

	void passage12_Init()
	{
		this.Passages[@" End 3"] = new StoryPassage(@" End 3", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"Feel free to come back here tomorrow too,\" she says with a wink. \"Always nice to have someone interesting to talk to.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("A phone rings behind the counter, and she sighs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Excuse me for a moment, I'll be right back with your check, hon.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait for the check. ", " End 3.5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13:  Old Man Lead 2

	void passage13_Init()
	{
		this.Passages[@" Old Man Lead 2"] = new StoryPassage(@" Old Man Lead 2", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"Golly, you must be a detective to figure that out!\" she says with a smile. \"Jokes aside, I'm not sure what I really think...Gary has been in a rage since the fire. Claims some teens were up to funny business on his land and started the fire. I'm normally not inclined to believe him, but...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The waitress is suddenly quiet, looking a bit distracted.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Everything alright?\" ", " Old Man 3", null);
		yield return lineBreak();
		yield return link("\"What kind of funny business are we talking about here?\" ", " Old Man 3.5", null);
		yield break;
	}


	// .............
	// #14:  Old Man 3

	void passage14_Init()
	{
		this.Passages[@" Old Man 3"] = new StoryPassage(@" Old Man 3", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("\"Just a little chilly in here,\" she mumbles with a shrug. \"But, about those kids...Old Gary says they're satanists, wrapped up in some unholy business. I don't really know what's going on, but the whole thing gives me a bad feeling.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I could try looking into it, if it would make you feel any better.\" ", " Old Man 4", null);
		yield break;
	}


	// .............
	// #15:  Old Man 3.5

	void passage15_Init()
	{
		this.Passages[@" Old Man 3.5"] = new StoryPassage(@" Old Man 3.5", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\"I'm not very sure myself!\" Linda exclaims with wide eyes. \"Satanism, animal sacrifice...there are all kinds of nasty rumors out there about these kids. But who can really know what actually happened?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Maybe someone should get to the bottom of it.\" ", " Old Man 4", null);
		yield break;
	}


	// .............
	// #16:  Old Man 4

	void passage16_Init()
	{
		this.Passages[@" Old Man 4"] = new StoryPassage(@" Old Man 4", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("She gives a sly wink.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Well, aren't you a brave one?\" she says. \"Honestly, the whole town and I would sleep easier if someone cleared that whole mess up. More coffee, dear?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That would be great. Thanks.\" ", " End", null);
		yield break;
	}


	// .............
	// #17:  End

	void passage17_Init()
	{
		this.Passages[@" End"] = new StoryPassage(@" End", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("She fills up your mug with speed and precision, no doubt from years of experience.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I'll be back soon with the check, hon, so sit tight.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("With a smirk, Linda goes off behind the counter. Still, you're a bit unsettled by what she said. Satanists? Burning down churches? This didn't sound like anything you wanted to be wrapped up in...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Head out of the diner. ", " EndDia", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #18:  EndDia

	void passage18_Init()
	{
		this.Passages[@" EndDia"] = new StoryPassage(@" EndDia", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		macros2.EndDialogue("  ");
		yield break;
	}


	// .............
	// #19:   EndDia

	void passage19_Init()
	{
		this.Passages[@"  EndDia"] = new StoryPassage(@"  EndDia", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		macros2.EndDialogue(" ");
		yield break;
	}


	// .............
	// #20:  Orphanage Lead 2

	void passage20_Init()
	{
		this.Passages[@" Orphanage Lead 2"] = new StoryPassage(@" Orphanage Lead 2", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Linda chuckles, rolling her eyes.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Yeah, troublemakers,\" she says. \"I ain't ever seen it for myself, but I've heard on the grapevine that these kids are thieves, vandals, druggies...the whole lot. Can't say I blame them though. What else are you supposed to do when life throws you into a hole besides bury yourself? More coffee dear?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That would be great. Thanks.\" ", "End", null);
		yield break;
	}


	// .............
	// #21:  Orphanage Lead 2.5

	void passage21_Init()
	{
		this.Passages[@" Orphanage Lead 2.5"] = new StoryPassage(@" Orphanage Lead 2.5", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Linda suddenly looks annoyed, a frown on her lips.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"For a day or two, maybe,\" she says. \"But it didn't take long for them to forget about it. Alcohol will do that, you know?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("She shakes her head in disgust.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I used to donate money to the orphanage, you know? Just a dollar or two each month, since serving tables barely pays the bills. But by God, I thought I was doing something good. Guess it didn't matter in the end.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("She sighs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"The truth is, most of the townspeople didn't give a damn about the those kids. Never did, and still don't even when they were taken before their time. Oh, it makes me furious...!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("There's an awkward silence as the waitress fumes, the tips of her ears turning red. I decide to stay quiet. Eventually, she seems to calm down.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"More coffee?\" she offers.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks.\" ", "End", null);
		yield break;
	}


	// .............
	// #22: End

	void passage22_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("She fills up your mug with speed and precision, no doubt from years of experience.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I'll be back soon with the check, hon, so sit tight.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait for the check. ", " End 1.5", null);
		yield break;
	}


	// .............
	// #23:  Diner 1.5

	void passage23_Init()
	{
		this.Passages[@" Diner 1.5"] = new StoryPassage(@" Diner 1.5", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("\"Hey, mister,\" says the girl at the front booth. \"Table for one?\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You nod, and she gives you a quick smile before she grabs a menu and leads you to a seat at the counter.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"What can I get for you today, hon?\" she says as she pulls out a notepad from her waist pocket. \"Special of the day is a three egg omelette with all the fixings.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Just a coffee for me.\" ", " Diner 2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #24:  Diner 5.5

	void passage24_Init()
	{
		this.Passages[@" Diner 5.5"] = new StoryPassage(@" Diner 5.5", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("\"I'm sure the sheriff told you about Old Gary and his crazy claims,\" she eventually says. \"But did you hear about the orphanage? Or the parents who lost their daughter on the night of the fire? Real upset, those two...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Tell me more about the old man and the church that burned down.\" ", "Dolls Lead", null);
		yield return lineBreak();
		yield return link("\"You mentioned a girl died during the fire, and her parents were really upset. What's that all about?\" ", "Old Man Lead", null);
		yield return lineBreak();
		yield return link("\"I've heard a bit about the orphanage, but nothing detailed. Can you give me some info?\" ", " Orphanage Lead", null);
		yield break;
	}


	// .............
	// #25:  End 3.5

	void passage25_Init()
	{
		this.Passages[@" End 3.5"] = new StoryPassage(@" End 3.5", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("After she comes back with the check, you lean back in your seat and take a deep breath. Something felt weird here. How else would that girl have died, if not in the fire? Whatever was going on, you were getting anxious to get some answers...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Head out from the diner. ", "  EndDia", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #26:  Orphan 1.5

	void passage26_Init()
	{
		this.Passages[@" Orphan 1.5"] = new StoryPassage(@" Orphan 1.5", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("\"Those kids didn't deserve it, you know? Never had parents, never had a real place to call home, but at the end of the day it's all the luck of the draw. Damn shame. Real damn shame. Even if they were nothing but rascals and troublemakers.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Troublemakers?\" ", " Orphanage Lead 2", null);
		yield return lineBreak();
		yield return link("\"I'm sorry. It must have been a real shock for the townspeople.\" ", " Orphanage Lead 2.5", null);
		yield break;
	}


	// .............
	// #27:  End 1.5

	void passage27_Init()
	{
		this.Passages[@" End 1.5"] = new StoryPassage(@" End 1.5", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("With a smirk, Linda returns with the check. After you pay, you start to ponder the odd rumors she shared with you. A whole orphanage burns to the ground with no survivors, and no one cared? Sounded just a bit suspicious...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Head out from the diner. ", "  EndDia", null);
		yield break;
	}


}