/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Fireman.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Fireman: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@Fireman()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Intro

	void passage1_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Afternoon detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"How bad is it?\"", "Bad", null);
		yield return lineBreak();
		yield return link("\"Any idea what started it?\"", "Church", null);
		yield break;
	}


	// .............
	// #2: Bad

	void passage2_Init()
	{
		this.Passages[@"Bad"] = new StoryPassage(@"Bad", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Bad. We're lucky it didn't take the whole town. It started in the old church. The wind pushed it across the dry fields, burning down a number of farms. It eventually stopped spreading when the snow started coming down, but by then it had nearly half the town: houses, shops, even the old orphanage.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"The church. Any idea what started it?\"", "No.", null);
		yield break;
	}


	// .............
	// #3: Church

	void passage3_Init()
	{
		this.Passages[@"Church"] = new StoryPassage(@"Church", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("It started in the old church. The wind pushed it across the dry fields, all the way into town. We got off lucky.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Any idea what started it?\"", "No.", null);
		yield break;
	}


	// .............
	// #4: No.

	void passage4_Init()
	{
		this.Passages[@"No."] = new StoryPassage(@"No.", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"We don't know much yet. The church has been abandoned for decades. We have a newer one built closer to town. We know it's not an eletrical fire because the building never had any electricity. It had an antebellum gas lighting system, but that should have been disconnected long ago.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Is there any chance it wasn't?\"", "Maybe", null);
		yield return lineBreak();
		yield return link("\"Keep me updated. Tell me if you find anything near the scene.\"", "End", null);
		yield return lineBreak();
		yield return link("\"Why was the church abandoned?\"", "TalkTo", null);
		yield break;
	}


	// .............
	// #5: End

	void passage5_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		macros2.EndDialogue("420");
		yield break;
	}


	// .............
	// #6: TalkTo

	void passage6_Init()
	{
		this.Passages[@"TalkTo"] = new StoryPassage(@"TalkTo", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Asthbestos, I think. It was be fore my time. Pastor Mike probably knows more.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Huh. Keep me updated. Tell me if you find anything in the old church.\"", "End", null);
		yield break;
	}


	// .............
	// #7: Maybe

	void passage7_Init()
	{
		this.Passages[@"Maybe"] = new StoryPassage(@"Maybe", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Maybe. It seems unlikely, but if it wasn't a gas leak would be entirely plausible. I'll check the records. Someone must have inspected the building at some point.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Keep me updated. Tell me if you find anything.\"", "End", null);
		yield break;
	}


}