/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Innkeeper.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Innkeeper: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@Innkeeper()
	{
		this.StartPassage = "HI INGRID";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: HI INGRID

	void passage1_Init()
	{
		this.Passages[@"HI INGRID"] = new StoryPassage(@"HI INGRID", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros2.SetSpeaker("Innkeeper");
		yield return lineBreak();
		yield return text("\"Hey sweetie, how is the investigation going so far?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Good, I have a few leads?\" ", " Innkeeper leads", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Not that great.\" ", " Innkeeper leads", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Innkeeper leads

	void passage2_Init()
	{
		this.Passages[@" Innkeeper leads"] = new StoryPassage(@" Innkeeper leads", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Y'know, this is a small town and not a lot stays secret. A lot of news comes through here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Oh, what do you know?\"", "\"Oh, what do you know?\"", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: ""Oh, what do you know?""

	void passage3_Init()
	{
		this.Passages[@"""Oh, what do you know?"""] = new StoryPassage(@"""Oh, what do you know?""", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"What do you want to know?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's the deal with that orphan hanging around here?\" ", " orphan", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Why does that old man hate the college kids?\" ", " old man", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's the deal with those rumors about the dead kid?\" ", " dead kid", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4:  orphan

	void passage4_Init()
	{
		this.Passages[@" orphan"] = new StoryPassage(@" orphan", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Oh, uh, I actually don't no what his deal is. I've never seen him before, but ever since the fire he's just been ... hanging around. He seems nice enough though, I guess.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Intesting.", "What else?", null);
		yield break;
	}


	// .............
	// #5:  old man

	void passage5_Init()
	{
		this.Passages[@" old man"] = new StoryPassage(@" old man", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"Ever since those kids came back for Christmas break they've been acting real strange, talking about fairies and stuff, hanging around in the old church. They've been driving Gary up the wall! He lives right next to that church. They hang out there drinking and smoking into the dead of night. And I don't mean cigarettes.\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Interesting.", "What else?", null);
		yield break;
	}


	// .............
	// #6:  dead kid

	void passage6_Init()
	{
		this.Passages[@" dead kid"] = new StoryPassage(@" dead kid", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"Oh, there's this whole legend that those people like to spread around. Something about some curse from the olden days or something. In my opinion, it's all a bunch of superstition. \"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Interesting.", "What else?", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: End

	void passage7_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros2.EndDialogue("");
		yield break;
	}


	// .............
	// #8: What else?

	void passage8_Init()
	{
		this.Passages[@"What else?"] = new StoryPassage(@"What else?", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"What else do you want to know?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's the deal with that orphan hanging around here?\" ", " orphan", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Why does that old man hate the college kids?\" ", " old man", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What's the deal with those rumors about the dead kid?\" ", " dead kid", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I think I'm done here.\"", "End", null);
		yield break;
	}


}