/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Jonah.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Jonah: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Fae", () => this.@Fae, val => this.@Fae = val);
		}

		public StoryVar @Fae;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@Jonah()
	{
		this.StartPassage = "What's up?";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: What's up?

	void passage1_Init()
	{
		this.Passages[@"What's up?"] = new StoryPassage(@"What's up?", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Good Evening, Officer\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Where were you the night of the fire?\"", "in the church", null);
		yield break;
	}


	// .............
	// #2: in the church

	void passage2_Init()
	{
		this.Passages[@"in the church"] = new StoryPassage(@"in the church", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"We were hanging out in the old church like we do sometimes.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Just 'hanging out'? In an old church?\"-", "well", null);
		yield return lineBreak();
		yield return link("\"That's where the fire started. What do you know about that?\"", "nothing", null);
		yield break;
	}


	// .............
	// #3: well

	void passage3_Init()
	{
		this.Passages[@"well"] = new StoryPassage(@"well", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Nobody used the place for years. We didn't think anyone would mind.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"The fire started in the church. What do you know about that?\"", "nothing", null);
		yield break;
	}


	// .............
	// #4: nothing

	void passage4_Init()
	{
		this.Passages[@"nothing"] = new StoryPassage(@"nothing", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Nothing. The fire started after we left.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Did leave anything behind that could have started a fire?\"", "cig", null);
		yield break;
	}


	// .............
	// #5: cig

	void passage5_Init()
	{
		this.Passages[@"cig"] = new StoryPassage(@"cig", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"Well, we had a cigerett or two, but we snuffed them all out.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"If not you, then who?\"", "\"If not you, then who?\"", null);
		yield break;
	}


	// .............
	// #6: ""If not you, then who?""

	void passage6_Init()
	{
		this.Passages[@"""If not you, then who?"""] = new StoryPassage(@"""If not you, then who?""", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Jonah goes white.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"No idea, Detective.\"");
		yield return lineBreak();
		yield return lineBreak();
		macros4.ImportVar("Fae");
		yield return lineBreak();
		yield return lineBreak();
		if(Vars.Fae == true) {
			yield return lineBreak();
			yield return link("\"Your friends say they saw something.\"", "\"Your friends say they saw something.\"", null);
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Hm. Have a nice day.\"", "end", null);
		yield break;
	}


	// .............
	// #7: ""Your friends say they saw something.""

	void passage7_Init()
	{
		this.Passages[@"""Your friends say they saw something."""] = new StoryPassage(@"""Your friends say they saw something.""", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"My friends have good imaginations.\"");
		yield return lineBreak();
		yield return text("Despite the confidence of the statement, his voice shook.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Indeed they do.\"", "end", null);
		yield return lineBreak();
		yield return link("\"You saw something too, didn't you?\"", "idk", null);
		yield break;
	}


	// .............
	// #8: end

	void passage8_Init()
	{
		this.Passages[@"end"] = new StoryPassage(@"end", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		macros3.ChangeScene("Fae_Park");
		yield break;
	}


	// .............
	// #9: idk

	void passage9_Init()
	{
		this.Passages[@"idk"] = new StoryPassage(@"idk", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"I don't know what I saw. Or heard. A trick of the light. Some kid in a costume maybe.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Interesting theories. Thank you for your time.\"", "end", null);
		yield break;
	}


}