/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: MeetingTheSheriff.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @MeetingTheSheriff: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@MeetingTheSheriff()
	{
		this.StartPassage = "Arrival";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Arrival

	void passage1_Init()
	{
		this.Passages[@"Arrival"] = new StoryPassage(@"Arrival", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Well, I'll be,\" says the sheriff. \"You must be that investigator from the city. Pleasure to meet you.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Pleasure's all mine.\" ", " Sheriff 1", null);
		yield return lineBreak();
		yield return link("Shake his hand but say nothing. ", " Sheriff 1", null);
		yield break;
	}


	// .............
	// #2:  Sheriff 1

	void passage2_Init()
	{
		this.Passages[@" Sheriff 1"] = new StoryPassage(@" Sheriff 1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Let's get right down to business,\" he says, a sudden change of tone. \"I'm hoping you read that case file we sent over.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Sure did. Been a while since I've seen a fire this bad.\" ", " Sheriff 2", null);
		yield break;
	}


	// .............
	// #3:  Sheriff 2

	void passage3_Init()
	{
		this.Passages[@" Sheriff 2"] = new StoryPassage(@" Sheriff 2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"That's no surprise,\" he coughs roughly. \"Firefighters could hardly keep the damn thing from scorching the town to oblivion. But they did, thank the lord. Good men, they are. Glad none of them got hurt in the whole ordeal.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"The case file didn't list a reason for the fire. Any clue what could have started it?\" ", " Sheriff 3", null);
		yield break;
	}


	// .............
	// #4:  Sheriff 3

	void passage4_Init()
	{
		this.Passages[@" Sheriff 3"] = new StoryPassage(@" Sheriff 3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("The sheriff rolls his eyes.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Oh, we have some leads,\" he laughs. \"Old Gary is at it again, claiming some college kids burned down the church on his land and started the whole fire. Threatening to sue and have them locked up for life. Typical Gary.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Do you think these college kids did it?\" ", " Sheriff 4", null);
		yield break;
	}


	// .............
	// #5:  Sheriff 4

	void passage5_Init()
	{
		this.Passages[@" Sheriff 4"] = new StoryPassage(@" Sheriff 4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"Hard to say what I believe,\" he says after a brief moment. \"Don't get me wrong, I always take whatever Old Gary says with a hint of salt, but this time it seems more plausible than usual...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The sheriff is suddenly silent, as if deep in thought.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Anyways,\" he continues, \"a gas leak is the most likely cause of the fire. Or that's what the firefighters told me, at least. They said a leak under the orphanage lit the whole place up like a candle.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"So the fire started at the orphanage? Or the church?\" ", " Sheriff 5", null);
		yield break;
	}


	// .............
	// #6:  Sheriff 5

	void passage6_Init()
	{
		this.Passages[@" Sheriff 5"] = new StoryPassage(@" Sheriff 5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"We're not sure exactly,\" he says, a little annoyed. \"We've been a little busy with rebuilding and making sure the people who lost their homes aren't out on the streets this winter. My apologies if we haven't solved your case for you yet.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Things are a bit tense now, and you decide it best to change the topic.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'll start on the case in a bit. Know where someone can find a decent meal in this town?\" ", " Sheriff 6", null);
		yield return lineBreak();
		yield return link("\"Is there anyone else I can ask for information on the fire?\" ", " Sheriff 6", null);
		yield break;
	}


	// .............
	// #7:  Sheriff 6

	void passage7_Init()
	{
		this.Passages[@" Sheriff 6"] = new StoryPassage(@" Sheriff 6", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"The diner isn't a bad place to be,\" the sheriff says, \"whether you're looking for food or rumors. It's across the street from the station. I can have an officer show you down there, if you'd like.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'll be alright, thanks.\" ", " Sheriff 7", null);
		yield break;
	}


	// .............
	// #8:  Sheriff 7

	void passage8_Init()
	{
		this.Passages[@" Sheriff 7"] = new StoryPassage(@" Sheriff 7", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Take care of yourself,\" he says with a nod and a pat on the shoulder. \"Things in this town haven't been the same since the fire, and I can't quite explain it, but...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The sheriff trails off.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Take care of yourself,\" he repeats.");
		yield return lineBreak();
		yield return lineBreak();
		macros2.EndDialogue(" ");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


}