/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: NewChurch.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @NewChurch: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@NewChurch()
	{
		this.StartPassage = "NewChurch";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: NewChurch

	void passage1_Init()
	{
		this.Passages[@"NewChurch"] = new StoryPassage(@"NewChurch", new string[]{ "Start", }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("Knock on the door.", "Knock", null);
		yield return text(" ");
		yield return lineBreak();
		yield return link("Leave", "End", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Second

	void passage2_Init()
	{
		this.Passages[@" Second"] = new StoryPassage(@" Second", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		using (Group("bold", true)) {
			yield return text("This");
		}
		yield return text(" --is-- so sad");
		yield return lineBreak();
		yield return text("Alexa, play Despacito");
		yield break;
	}


	// .............
	// #3: Forest - Clearing

	void passage3_Init()
	{
		this.Passages[@"Forest - Clearing"] = new StoryPassage(@"Forest - Clearing", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Entering a clearing laced with a grey haze, patches of char sprinkled with ash, you cough reflexively to purge your lungs of a foul scent. Dead aspens splinter the ground to commemorate the town's best birthday cake. ");
		yield return lineBreak();
		yield return text("--WIP--");
		yield break;
	}


	// .............
	// #4: Knock

	void passage4_Init()
	{
		this.Passages[@"Knock"] = new StoryPassage(@"Knock", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("The door opens slightly,");
		yield return lineBreak();
		yield return text("just enough for a pair of beady eyes to glisten out at you.");
		yield return lineBreak();
		yield return text("You prepare to address the person behind the door,");
		yield return lineBreak();
		yield return text("but before you can even part your lips, the door slams shut.");
		yield return lineBreak();
		yield return link("Knock again.", "KnockAgain", null);
		yield return text(" ");
		yield return lineBreak();
		yield return link("Leave.", "End", null);
		yield break;
	}


	// .............
	// #5: KnockAgain

	void passage5_Init()
	{
		this.Passages[@"KnockAgain"] = new StoryPassage(@"KnockAgain", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("No response.");
		yield return lineBreak();
		yield return text("It doesn't seem like the person behind the door");
		yield return lineBreak();
		yield return text("will respond to courtesies.");
		yield return lineBreak();
		yield return text("Maybe you should try a different tactic.");
		yield return lineBreak();
		yield return link("Talk through the door.", "Talk", null);
		yield return lineBreak();
		yield return link("Leave.", "End", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #6: End

	void passage6_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		macros2.EndDialogue("end");
		yield break;
	}


	// .............
	// #7: Talk

	void passage7_Init()
	{
		this.Passages[@"Talk"] = new StoryPassage(@"Talk", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Excuse me,\" you say, \"I'd like to ask you a few questions.\"");
		yield return lineBreak();
		yield return text("\"Go Away.\" The voice behind the door, a woman, responds.");
		yield return lineBreak();
		yield return text("Maybe they think you're an Evangelist.");
		yield return lineBreak();
		yield return link("\"Do you know anything about the recent fire?\"", "Polite", null);
		yield return lineBreak();
		yield return link("\"Open the damn door before I kick it down myself.\"", "Rude", null);
		yield break;
	}


	// .............
	// #8: Polite

	void passage8_Init()
	{
		this.Passages[@"Polite"] = new StoryPassage(@"Polite", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Yes. It was hot. Now fuck off.\"");
		yield return lineBreak();
		yield return text("How rude. This woman has a pretty short temper.");
		yield return lineBreak();
		yield return link("Try saying something else.", "Talk", null);
		yield break;
	}


	// .............
	// #9: Rude

	void passage9_Init()
	{
		this.Passages[@"Rude"] = new StoryPassage(@"Rude", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("As soon as those words leave your mouth, the door flies open,");
		yield return lineBreak();
		yield return text("and you're greeted with the angry face of a middle-aged woman.");
		yield return lineBreak();
		yield return text("Her eyes are burning with a cold, fiery malice.");
		yield return lineBreak();
		yield return link("Steel yourself for a possible fight.", "PrepareFight", null);
		yield break;
	}


	// .............
	// #10: PrepareFight

	void passage10_Init()
	{
		this.Passages[@"PrepareFight"] = new StoryPassage(@"PrepareFight", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("You're ready to start throwing hands,");
		yield return lineBreak();
		yield return text("when a second head pops into the doorframe.");
		yield return lineBreak();
		yield return text("A man, the striking image of a typical white-collar American,");
		yield return lineBreak();
		yield return text("steps into view and casts you a worried look.");
		yield return lineBreak();
		yield return text("He steps in between you and the woman and smiles sympathetically.");
		yield return lineBreak();
		yield return text("\"Forgive us. My wife has had a tiring day, and was just");
		yield return lineBreak();
		yield return text("preparing to get some much needed rest. Isn't that right, dear?\"");
		yield return lineBreak();
		yield return text("The woman, her expression softening slightly, perhaps because");
		yield return lineBreak();
		yield return text("of the presence of her husband, casts you a dark but tired glare");
		yield return lineBreak();
		yield return text("before retreating into her home.");
		yield return lineBreak();
		yield return link("Greet the man.", "GreetMan", null);
		yield return lineBreak();
		yield return link("Apologize and leave.", "End", null);
		yield break;
	}


	// .............
	// #11: GreetMan

	void passage11_Init()
	{
		this.Passages[@"GreetMan"] = new StoryPassage(@"GreetMan", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("The man smiles again.");
		yield return lineBreak();
		yield return text("\"I apologize for the scare.");
		yield return lineBreak();
		yield return text("We've had a rather... troubling time.\"");
		yield return lineBreak();
		yield return text("How do you respond?");
		yield return lineBreak();
		yield return link("\"The sheriff send me here. He told me you were one of the first people to see the fire break out that night.\"", "SheriffSent", null);
		yield return lineBreak();
		yield return link("\"Sorry to bother you, but do you mind answering some questions about the fire?\"", "SorryBother", null);
		yield break;
	}


	// .............
	// #12: SheriffSent

	void passage12_Init()
	{
		this.Passages[@"SheriffSent"] = new StoryPassage(@"SheriffSent", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"He told you right. What do you want to know?\"");
		yield return lineBreak();
		yield return link("\"Well... let's start with...", "Questions", null);
		yield break;
	}


	// .............
	// #13: Questions

	void passage13_Init()
	{
		this.Passages[@"Questions"] = new StoryPassage(@"Questions", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return link("\"Where were you that night?\"", "Where", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious?\"", "Suspicious", null);
		yield break;
	}


	// .............
	// #14: SorryBother

	void passage14_Init()
	{
		this.Passages[@"SorryBother"] = new StoryPassage(@"SorryBother", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("\"Not a problem. Although,");
		yield return lineBreak();
		yield return text("I'd appreciate it if you didn't threaten");
		yield return lineBreak();
		yield return text("to kick down the door of our brand new church.");
		yield return lineBreak();
		yield return text("The draft in the house is bad enough as it is. But ask away.\"");
		yield return lineBreak();
		yield return link("\"Well... Let's start with...", "Questions", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: Where

	void passage15_Init()
	{
		this.Passages[@"Where"] = new StoryPassage(@"Where", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("“My wife and I were out at the bar in town,");
		yield return lineBreak();
		yield return text("celebrating the end of another work week.");
		yield return lineBreak();
		yield return text("We left our child at home, you see.");
		yield return lineBreak();
		yield return text("We just needed some time to ourselves.\"");
		yield return lineBreak();
		yield return link("\"Did you notice anyone suspicious, or anything that was out of place?\"", "Suspicious", null);
		yield break;
	}


	// .............
	// #16: Suspicious

	void passage16_Init()
	{
		this.Passages[@"Suspicious"] = new StoryPassage(@"Suspicious", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\"Now that you mention it, Pastor Nick was strangely absent on that night.");
		yield return lineBreak();
		yield return text("He normally stays up late, but must've gone home early.\"");
		yield return lineBreak();
		yield return link("New lead: Old church", "End", null);
		yield return text(" ");
		yield break;
	}


}