/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: PastorMike.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @PastorMike: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@PastorMike()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"Hello. What brings you to the house of God?\"");
		yield return lineBreak();
		yield return link("\"I was wondering if you could tell me anything about the fire.\"", "AskFire", null);
		yield return lineBreak();
		yield return link("\"How have the townspeople been doing?\"", "AskPeople", null);
		yield return lineBreak();
		yield return link("\"Can you tell me about the history of this town?\"", "History", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious related to the fire?\"", "AskSus", null);
		yield return lineBreak();
		yield return link("\"I'm just here to interview a few people\"", "Interview", null);
		yield break;
	}


	// .............
	// #2: AskFire

	void passage2_Init()
	{
		this.Passages[@"AskFire"] = new StoryPassage(@"AskFire", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Ah. A beautiful structure. It's a shame we couldn't afford to maitain it. Between the mold, the rust, and the asbestos, you can only fight mortality for so long. But I suppose the fire took it before the decay did. I was told it began in my old church, and grew quickly to consume a few");
		yield return lineBreak();
		yield return text("surrounding houses. The couple living here lost their house, along with");
		yield return lineBreak();
		yield return text("their beloved daughter, God rest her soul.\"");
		yield return lineBreak();
		yield return link("\"Did the gas lines have any problems?\"", "Gas", null);
		yield return lineBreak();
		yield return link("\"You were told? Were you not in the church that night?\"", "Absence", null);
		yield return lineBreak();
		yield return link("\"How have the townspeople been doing?\"", "AskPeople", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious related to the fire?\"", "AskSus", null);
		yield break;
	}


	// .............
	// #3: AskSus

	void passage3_Init()
	{
		this.Passages[@"AskSus"] = new StoryPassage(@"AskSus", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"I'm terribly sorry. I wouldn't be able to tell you.");
		yield return lineBreak();
		yield return text("I was not present in the church that night");
		yield return lineBreak();
		yield return text("You might find some clues there, though.\"");
		yield return lineBreak();
		yield return link("\"Why weren't you in the church?\"", "Absence", null);
		yield return lineBreak();
		yield return link("\"What is left of the old church?\"", "Remains", null);
		yield break;
	}


	// .............
	// #4: AskPeople

	void passage4_Init()
	{
		this.Passages[@"AskPeople"] = new StoryPassage(@"AskPeople", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Recovering. But slowly. Everyone lost something in that fire.");
		yield return lineBreak();
		yield return text("The couple residing in this new church, most of all.\"");
		yield return lineBreak();
		yield return link("\"I was wondering if you could tell me anything about the fire.\"", "AskFire", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious related to the fire?\"", "AskSus", null);
		yield break;
	}


	// .............
	// #5: Absence

	void passage5_Init()
	{
		this.Passages[@"Absence"] = new StoryPassage(@"Absence", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"Erm, I was attending to some official church matters.");
		yield return lineBreak();
		yield return text("Also, even spiritual leaders need breaks every now and then.");
		yield return lineBreak();
		yield return text("Although, I regret not being there. Perhaps I could have been able");
		yield return lineBreak();
		yield return text("to do something.\"");
		yield return lineBreak();
		yield return text("Pastor Mike's eyes extinguish slightly, then gaze at you with a sudden glow.");
		yield return lineBreak();
		yield return text("\"Ah, there is something you could do.\"");
		yield return lineBreak();
		yield return link("\"Yes?\"", "WhatIsIt", null);
		yield break;
	}


	// .............
	// #6: Remains

	void passage6_Init()
	{
		this.Passages[@"Remains"] = new StoryPassage(@"Remains", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"The structure above ground is completely destroyed, anything below");
		yield return lineBreak();
		yield return text("ground is a different story.");
		yield return lineBreak();
		yield return text("If I had been there...\"");
		yield return lineBreak();
		yield return text("Pastor Mike's eyes extinguish slightly, then gaze at you with a sudden glow.");
		yield return lineBreak();
		yield return text("\"Ah, there is something you could do.\"");
		yield return lineBreak();
		yield return link("\"Yes?\"", "WhatIsIt", null);
		yield break;
	}


	// .............
	// #7: WhatIsIt

	void passage7_Init()
	{
		this.Passages[@"WhatIsIt"] = new StoryPassage(@"WhatIsIt", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"Some items of importance was left in the basement of the old church.");
		yield return lineBreak();
		yield return text("The old church had solid stone foundations, so the basement");
		yield return lineBreak();
		yield return text("was largely untouched.");
		yield return lineBreak();
		yield return text("Could I trouble you to retrieve a chest of my old books?");
		yield return lineBreak();
		yield return text("I haven't been able to go myself as of late, and you may find some");
		yield return lineBreak();
		yield return text("clues while you're there.\"");
		yield return lineBreak();
		yield return link("Leave", "End", null);
		yield break;
	}


	// .............
	// #8: End

	void passage8_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		macros2.EndDialogue("end");
		yield break;
	}


	// .............
	// #9: Interview

	void passage9_Init()
	{
		this.Passages[@"Interview"] = new StoryPassage(@"Interview", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"Well go ahead. Just keep in mind that these people have been through much trauma, so choose your words wisely.\"");
		yield return lineBreak();
		yield return link("Leave", "End", null);
		yield break;
	}


	// .............
	// #10: Gas

	void passage10_Init()
	{
		this.Passages[@"Gas"] = new StoryPassage(@"Gas", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"The gas was broken even before I started preaching there. There were always more urgent matters to deal with. When I got put in charge I had it permenantely disabled for safety reasons. So even if the pipes leaked,");
		yield return lineBreak();
		yield return text("there would be no gas.\"");
		yield return lineBreak();
		yield return link("\"Were you not in the church that night?\"", "Absence", null);
		yield return lineBreak();
		yield return link("\"How have the townspeople been doing?\"", "AskPeople", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious related to the fire?\"", "AskSus", null);
		yield break;
	}


	// .............
	// #11: History

	void passage11_Init()
	{
		this.Passages[@"History"] = new StoryPassage(@"History", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("\"Let's see. Founded by Anston Blackwood. Officially chartered in 1789. Survived one hundred eighty winters, through war and famine alike. Population never rose above 700. There have been a handful of tragedies.");
		yield return lineBreak();
		yield return text("The locals sometimes talk about the town being \"cursed\", but it's all just superstition, I assure you.\"");
		yield return lineBreak();
		yield return link("\"I was wondering if you could tell me anything about the fire.\"", "AskFire", null);
		yield return lineBreak();
		yield return link("\"How have the townspeople been doing?\"", "AskPeople", null);
		yield return lineBreak();
		yield return link("\"Did you notice anything suspicious related to the fire?\"", "AskSus", null);
		yield break;
	}


}