/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Prologue_Case_Intro.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Prologue_Case_Intro: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@Prologue_Case_Intro()
	{
		this.StartPassage = "Case File";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Case File

	void passage1_Init()
	{
		this.Passages[@"Case File"] = new StoryPassage(@"Case File", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("The office is dark. Once again, you're the last one at work. Not that you mind that: it was easier to work when you had to whole place to yourself.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("A lone case file lies on your desk. You haven't had time to look over it yet, but you know it has to be important when the boss personally came to your desk to deliver it. The Christmas season was always a busy time for insurance investigators, and this was just one more log on the fire...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Open the file. ", " Case File 2", null);
		yield break;
	}


	// .............
	// #2:  Case File 2

	void passage2_Init()
	{
		this.Passages[@" Case File 2"] = new StoryPassage(@" Case File 2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("The case seems simple enough. Fire in a rural town, out in the boondocks. Hopefully it would be a quick visit.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Some small details on the case file eventually come to your attention, however. No official cause for the fire. Entire sections of the town burned to a crisp. Reports of missing children.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Suddenly, things were looking a bit more interesting.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Check the plane ticket. ", " Case File 3", null);
		yield break;
	}


	// .............
	// #3:  Case File 3

	void passage3_Init()
	{
		this.Passages[@" Case File 3"] = new StoryPassage(@" Case File 3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("8 AM departure, tomorrow. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Better head home and get some shut-eye. ");
		yield return lineBreak();
		yield return lineBreak();
		macros2.EndDialogue(" ");
		yield break;
	}


}