/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Tina_Kindsberg.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Tina_Kindsberg: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("Fae", () => this.@Fae, val => this.@Fae = val);
		}

		public StoryVar @Fae;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly HOOK macros2;
	public readonly DialogueEnder macros3;
	public readonly GlobalVarMacros macros4;

	@Tina_Kindsberg()
	{
		this.StartPassage = "What";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new HOOK() { Story = this };
		macros3 = new DialogueEnder() { Story = this };
		macros4 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: What

	void passage1_Init()
	{
		this.Passages[@"What"] = new StoryPassage(@"What", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("\"What do you want?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I want you to tell me how the fire started.\"", "faries", null);
		yield break;
	}


	// .............
	// #2: faries

	void passage2_Init()
	{
		this.Passages[@"faries"] = new StoryPassage(@"faries", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Fairies,\" she snaps.");
		yield return lineBreak();
		yield return text("\"You won't believe me, but it was the faries.\"");
		yield return lineBreak();
		yield return text("She says this with a disconcerting degree of confidence.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'm sorry, what?\"", "is", null);
		yield return lineBreak();
		yield return lineBreak();
		Vars.Fae  = true;
		yield return lineBreak();
		macros4.ExportVar("Fae");
		yield break;
	}


	// .............
	// #3: is

	void passage3_Init()
	{
		this.Passages[@"is"] = new StoryPassage(@"is", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"I said you wouldn't believe me. They were mad at us for some reason, and so the started the fire.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thank you for your... helpful insights.\"", "end", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"What makes you so certain about that?\"", "saw", null);
		yield break;
	}


	// .............
	// #4: saw

	void passage4_Init()
	{
		this.Passages[@"saw"] = new StoryPassage(@"saw", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"We saw them. One. Just like how old folktales describe them. I've studied these things. Stories. Mythologies. At School. Took a class.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Well, thank you for your helpful... insights.\"", "end", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Okay, so why did this... \\\"fairy\\\" go crazy and burn down the church?\"", "rules", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: end

	void passage5_Init()
	{
		this.Passages[@"end"] = new StoryPassage(@"end", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("This girl is in clear need of some fresh air. Best not to waste her time any further.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Back to the others", "Back to the others", null);
		yield break;
	}


	// .............
	// #6: rules

	void passage6_Init()
	{
		this.Passages[@"rules"] = new StoryPassage(@"rules", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Delighted at a chance to spill her knowlege, the suspect relaxes and begins chattering.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Well, the fairies mentioned in eastern european cultures often vary from mischevious to downright malevolent, but in more costal cultures are described as having arbitrary rules and motives which...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("...", "...", null);
		yield break;
	}


	// .............
	// #7: ...

	void passage7_Init()
	{
		this.Passages[@"..."] = new StoryPassage(@"...", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("(This goes on for a full minute-and-a-half.)");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"...but that varies based on historical context, mainly due to clerical supression. The translation is dodgy, and I haven't taken the course on eastern mythologies yet, so the distinction remains a mystery to me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Well, thank you for your... helpful... insights.\"", "end", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You still haven't given me a motive.\"", "anything", null);
		yield break;
	}


	// .............
	// #8: anything

	void passage8_Init()
	{
		this.Passages[@"anything"] = new StoryPassage(@"anything", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("The girl looks at you like you just interrupted a very important presentation.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"The point is, faries are easily offended and prone to violent outbursts. I wouldn't be surprised if they started the fire just because we made our sandwiches in the wrong order.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Well, thank you for your helpful insights.\"", "end", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"You had sandwiches?\"", "eh?", null);
		yield break;
	}


	// .............
	// #9: eh?

	void passage9_Init()
	{
		this.Passages[@"eh?"] = new StoryPassage(@"eh?", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"That was just an example. We were giving Jonah crap the other day because he makes his PB&J's the wrong way.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Well, thank you for your very helpful insights.\"", "end", null);
		yield return lineBreak();
		yield return lineBreak();
		macros4.ExportVar("PB&J");
		yield break;
	}


	// .............
	// #10: Back to the others

	void passage10_Init()
	{
		this.Passages[@"Back to the others"] = new StoryPassage(@"Back to the others", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		macros3.ChangeScene("Fae_Park");
		yield break;
	}


}