/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: EncounterWithTheCollegeKids.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @EncounterWithTheCollegeKids: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@EncounterWithTheCollegeKids()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("D: “Are you guys the college students? Do you guys have any information about the fire?” Student A: (she wears a little fake wing): \"People think that we did it. However, we just went inside the church to find the mystery.\"", " Convo2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Convo2

	void passage2_Init()
	{
		this.Passages[@" Convo2"] = new StoryPassage(@" Convo2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return link("D: \"What is this mystery that you are talking about?\" Student B (regular boy): \"I swear it's the fae. It needs to be the fae.\"", " Convo3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3:  Convo3

	void passage3_Init()
	{
		this.Passages[@" Convo3"] = new StoryPassage(@" Convo3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return link("D: “Fae? What do you mean by that?” Student A: \"The fae lives underground of the town. I promise it was the fae who caused the fire. We have disturbed the sacred place.\"", " Convo5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4:  Convo5

	void passage4_Init()
	{
		this.Passages[@" Convo5"] = new StoryPassage(@" Convo5", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return link("D: \"Sacred place? What do you mean?\" Student C (regular dressed girl): \"It's the legend of this town. The legend has been passed down for ages. It states that the fae has protected the town by the forest and was a guardian of the town. However, it has been excommunicated by the town in the past, and it hid hitself to an unknown place.\"", " Convo6", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5:  Convo6

	void passage5_Init()
	{
		this.Passages[@" Convo6"] = new StoryPassage(@" Convo6", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return link("D: “So with this legend, why do you guys think the fire has been caused?” Student A: \"I think that we may have found where the fae lives. We may have disturbed the fae.” ", " Convo7", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6:  Convo7

	void passage6_Init()
	{
		this.Passages[@" Convo7"] = new StoryPassage(@" Convo7", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return link("D: \"Where does the fae live? Have you guys actually seen the fae?” Student C: \"I promise I saw it! I saw the wings and the long hair.\" D:\"Where does the fae live?\" Student B: \"Underneath the church. It's not there anymore, but that is where Fae lives.\"", " Convo9", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7:  Convo9

	void passage7_Init()
	{
		this.Passages[@" Convo9"] = new StoryPassage(@" Convo9", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return link("D: “So there is a fae, and you guys went inside the church and accidentally angered the fae by infiltrating where it lives?” Student A B C (in unison) \"Yes!” ", " Convo12", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8:  Convo12

	void passage8_Init()
	{
		this.Passages[@" Convo12"] = new StoryPassage(@" Convo12", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return link("D: “I'll take it into consideration. Thank you guys for your time.” ", " Convo13", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9:  Convo13

	void passage9_Init()
	{
		this.Passages[@" Convo13"] = new StoryPassage(@" Convo13", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}