/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: FaeBeginning.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @FaeBeginning: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@FaeBeginning()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("*Townsperson comes to the detetice. T: I've seen those damn kids. I swear I saw them. They were the ones that caused the fire. Please trust me.", " Convo2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Convo2

	void passage2_Init()
	{
		this.Passages[@" Convo2"] = new StoryPassage(@" Convo2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return link("D: May I ask who you are, and when have you seen this? ", " Convo3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3:  Convo3

	void passage3_Init()
	{
		this.Passages[@" Convo3"] = new StoryPassage(@" Convo3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return link("T: I'm just a regular farmer. I've seen those kids at late night in the church. They were there, and I swear I saw them trying to cause a fire. ", " Convo4", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4:  Convo4

	void passage4_Init()
	{
		this.Passages[@" Convo4"] = new StoryPassage(@" Convo4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return link("D: \"Thank you. May I ask you where I can see those students?\" ", " Convo5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5:  Convo5

	void passage5_Init()
	{
		this.Passages[@" Convo5"] = new StoryPassage(@" Convo5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return link("T: \"You don't want to talk to them. All they're gonna do is lie. It's not even worth talking to them.\" D:\"Thank you for your information. I'll definitely get bottom of this.\"  ", " Convo7", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6:  Convo7

	void passage6_Init()
	{
		this.Passages[@" Convo7"] = new StoryPassage(@" Convo7", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}