/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: TheEndOfFae.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @TheEndOfFae: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@TheEndOfFae()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("D: “I'm going to conclude that it is the students. There is no such thing as fae, and they must have done it” ", " Convo2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  Convo2

	void passage2_Init()
	{
		this.Passages[@" Convo2"] = new StoryPassage(@" Convo2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return link("Townspeople: \"We should kick them out! They don't deserve to live here!\" ", " Convo3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3:  Convo3

	void passage3_Init()
	{
		this.Passages[@" Convo3"] = new StoryPassage(@" Convo3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return link("Students A B C: \"We promise that we didnt do it.\" *Gets kicked out of the town* ", " Convo4", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4:  Convo4

	void passage4_Init()
	{
		this.Passages[@" Convo4"] = new StoryPassage(@" Convo4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("[");
		yield return text("[");
		using (Group("em", true)) {
			yield return text("The night comes");
		}
		yield return text(". There is a shadow that appears near the church with wings and it laughs. ");
		yield return text("*");
		yield return text("Is it one of the student? or is it actually a fae?\"");
		yield break;
	}


}