/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Test.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Test: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;

	@Test()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Here's some dialogue");
		yield return lineBreak();
		yield return link("Go Left", "Go Left", null);
		yield return lineBreak();
		yield return link("Go Right", "Go Right", null);
		yield break;
	}


	// .............
	// #2: Go Left

	void passage2_Init()
	{
		this.Passages[@"Go Left"] = new StoryPassage(@"Go Left", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Hop to the left");
		yield return lineBreak();
		yield return link("Go Back", "Start", null);
		yield break;
	}


	// .............
	// #3: Go Right

	void passage3_Init()
	{
		this.Passages[@"Go Right"] = new StoryPassage(@"Go Right", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("And a slide to the right");
		yield return lineBreak();
		yield return link("Go back", "Start", null);
		yield break;
	}


}