/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: WellPresent.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @WellPresent: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
	public readonly DialogueEnder macros2;
	public readonly GlobalVarMacros macros3;

	@WellPresent()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
		macros2 = new DialogueEnder() { Story = this };
		macros3 = new GlobalVarMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("You come to the base of a small hill crowned by a small well. A faint dirt path slopes up gently to the top.");
		yield return lineBreak();
		yield return link("Walk up to the well.", "Well", null);
		yield return lineBreak();
		yield return link("Leave.", "Leave", null);
		yield break;
	}


	// .............
	// #2: Well

	void passage2_Init()
	{
		this.Passages[@"Well"] = new StoryPassage(@"Well", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("The well is in a state of disrepair. Stone bricks lay strewn where the mortar wore away. The wooden roof is moldy and the beams are split.");
		yield return lineBreak();
		yield return link("Look down the well.", "LookDown", null);
		yield return lineBreak();
		yield return link("Leave.", "Leave", null);
		yield break;
	}


	// .............
	// #3: Leave

	void passage3_Init()
	{
		this.Passages[@"Leave"] = new StoryPassage(@"Leave", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		macros2.EndDialogue("end");
		yield break;
	}


	// .............
	// #4: LookDown

	void passage4_Init()
	{
		this.Passages[@"LookDown"] = new StoryPassage(@"LookDown", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Looking down the well, you expect it to be near bottomless. Instead, you see a solid layer of ground about 6 feet down. The dirt must have been washed in through a hole in the side of the decrepit stone sides. This well has not seen use for a long, long time.");
		yield return lineBreak();
		yield return link("Climb down into the well.", "ClimbDown", null);
		yield return lineBreak();
		yield return link("Leave.", "Leave", null);
		yield break;
	}


	// .............
	// #5: ClimbDown

	void passage5_Init()
	{
		this.Passages[@"ClimbDown"] = new StoryPassage(@"ClimbDown", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Putting your hands and feet to the gaps in the mortar, you ease your way down a few feet before dropping to the bottom. You feel your feet land on something soft, fabric-like. You look down and see that it's a cloth doll with the appearance of a girl, dressed in a plaid dress and decorated with a blank expression.");
		yield return lineBreak();
		yield return link("Pick up the doll.", "PickUp", null);
		yield return lineBreak();
		yield return link("Leave.", "Leave", null);
		yield break;
	}


	// .............
	// #6: PickUp

	void passage6_Init()
	{
		this.Passages[@"PickUp"] = new StoryPassage(@"PickUp", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("You reach down slowly to the ground.");
		yield return lineBreak();
		yield return text("The air smells of sage and lemongrass.");
		yield return lineBreak();
		yield return text("Glancing over the doll, you notice it's yellowed clothes and");
		yield return lineBreak();
		yield return text("tattered texture. It must have been here for quite a while.");
		yield return lineBreak();
		yield return text("You reach out your hand and touch the doll on its head,");
		yield return lineBreak();
		yield return text("and everything");
		yield return lineBreak();
		yield return link("fades to white.", "End", null);
		yield break;
	}


	// .............
	// #7: End

	void passage7_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros2.EndDialogue("end");
		yield break;
	}


}